### ISSUE TITLE
Cannot find module './Imagefield'

### ISSUE THREAD

**Issue by fillipeweb** [romannurik/AndroidAssetStudio#136]
I have been having the following warning when a run npm install:

```
> undefined postinstall /home/fillipecordeiro/development/projects/javascript/AndroidAssetStudio
> bower install

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.17: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
```

And when I try to run gulp serve, the following issue:

```
Error: Cannot find module './Imagefield' from '/home/fillipecordeiro/development/projects/javascript/AndroidAssetStudio/app/scripts/studio/forms'
    at /home/fillipecordeiro/development/projects/javascript/AndroidAssetStudio/node_modules/browser-resolve/node_modules/resolve/lib/async.js:55:21
    at load (/home/fillipecordeiro/development/projects/javascript/AndroidAssetStudio/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/home/fillipecordeiro/development/projects/javascript/AndroidAssetStudio/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /home/fillipecordeiro/development/projects/javascript/AndroidAssetStudio/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:112:15)
```

What's happening?

Thanks.

**Comment by romannurik** [comment]
Whoops likely a typo that affects case sensitive file systems. Need to fix that to ImageField instead of lower case

**Comment by fillipeweb** [comment]
No problem, done :D
